# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Dzenis Madzovic\OneDrive - Högskolan Kristianstad\Skrivbordet\Projects\GoldApp\src\examples\card_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 312)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("margin-bottom: 8px;\n"
"max-height: 500px;\n"
"background:white;\n"
"border-radius: 5px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.photo = QtWidgets.QLabel(self.widget)
        self.photo.setMinimumSize(QtCore.QSize(109, 108))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo.setFont(font)
        self.photo.setStyleSheet("display: inline-block;\n"
"min-width: 100px;\n"
"min-height: 100px;\n"
"max-width: 300px;\n"
"max-height: 300px;\n"
"margin-left:9px;\n"
"border-radius: 3px;\n"
"")
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("c:\\Users\\Dzenis Madzovic\\OneDrive - Högskolan Kristianstad\\Skrivbordet\\Projects\\GoldApp\\src\\examples\\../image/chess.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setObjectName("photo")
        self.horizontalLayout_2.addWidget(self.photo)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.event = QtWidgets.QLabel(self.widget)
        self.event.setStyleSheet("font-size: 18px;")
        self.event.setObjectName("event")
        self.verticalLayout_4.addWidget(self.event)
        self.date = QtWidgets.QLabel(self.widget)
        self.date.setStyleSheet("font-size: 13px;")
        self.date.setObjectName("date")
        self.verticalLayout_4.addWidget(self.date)
        self.location = QtWidgets.QLabel(self.widget)
        self.location.setStyleSheet("font-size: 13px;")
        self.location.setObjectName("location")
        self.verticalLayout_4.addWidget(self.location)
        self.interest = QtWidgets.QLabel(self.widget)
        self.interest.setStyleSheet("font-size: 13px;")
        self.interest.setObjectName("interest")
        self.verticalLayout_4.addWidget(self.interest)
        self.description = QtWidgets.QLabel(self.widget)
        self.description.setStyleSheet("font-size: 13px;\n"
"min-height: 100px;\n"
"max-width: 300px;")
        self.description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description.setObjectName("description")
        self.verticalLayout_4.addWidget(self.description)
        self.read_more = QtWidgets.QPushButton(self.widget)
        self.read_more.setStyleSheet("QPushButton{\n"
"background-color:  rgb(255, 203, 99);\n"
"border: none;\n"
"border-radius: 10px;\n"
"color: white;\n"
"padding: 10px 23px;\n"
"margin: 10px 60px 10px 60px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"display: inline-block;\n"
"font-size: 13px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:  rgb(255, 220, 99);\n"
"}\n"
"")
        self.read_more.setObjectName("read_more")
        self.verticalLayout_4.addWidget(self.read_more)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.event.setText(_translate("Form", "Event<span class=\"event\">:</span>"))
        self.date.setText(_translate("Form", "Date & Time<span class=\"date\">:</span>"))
        self.location.setText(_translate("Form", "Location<span class=\"address\">:</span>"))
        self.interest.setText(_translate("Form", "Interest<span class=\"interest\">:</span>"))
        self.description.setText(_translate("Form", "Description<span class=\"desc\">:</span>"))
        self.read_more.setText(_translate("Form", "Read More"))
