# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meetings_events_all.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
import json

path = os.path.dirname(os.path.abspath(f"{__file__}\.."))
from show_events import show_events


class Ui_Form(object):
    def setupUi(self, Form):
        event_id_list = show_events()[0]
        Form.setObjectName("Form")
        Form.resize(800, 881)
        Form.setStyleSheet("background-color: rgb(220, 221, 255);")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMaximumSize(QtCore.QSize(1800, 900))
        self.widget_3.setStyleSheet("padding-left: 5cm;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.app_logo = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.app_logo.setFont(font)
        self.app_logo.setStyleSheet(
            "QLabel{\n"
            "color: rgb(255, 203, 99);\n"
            "background-color: white;\n"
            "border-color: black;\n"
            "border-radius: 10px;\n"
            "border-style: none;\n"
            "margin-top: 10px;\n"
            "margin-bottom: 10px;\n"
            "padding-left: 20px;\n"
            "padding-right: 20px;\n"
            "margin-left: 0px;\n"
            "margin-right: 0px;\n"
            "}"
        )
        self.app_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.app_logo.setObjectName("app_logo")
        self.horizontalLayout_5.addWidget(self.app_logo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_board = QtWidgets.QGridLayout()
        self.main_board.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setEnabled(True)
        self.widget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 9, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.events_location = QtWidgets.QLabel(self.widget_2)
        self.events_location.setMinimumSize(QtCore.QSize(404, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.events_location.setFont(font)
        self.events_location.setStyleSheet("")
        self.events_location.setScaledContents(False)
        self.events_location.setAlignment(QtCore.Qt.AlignCenter)
        self.events_location.setObjectName("events_location")
        self.horizontalLayout.addWidget(self.events_location)
        self.main_board.addWidget(self.widget_2, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setMinimumSize(600, 0)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 466, 710))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.photo = QtWidgets.QLabel(self.widget)
        self.photo.setMinimumSize(QtCore.QSize(109, 108))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo.setFont(font)
        self.photo.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../image/chess.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setObjectName("photo")
        self.horizontalLayout_2.addWidget(self.photo)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.event = QtWidgets.QLabel(self.widget)
        self.event.setStyleSheet("font-size: 18px;")
        self.event.setObjectName("event")
        self.verticalLayout_4.addWidget(self.event)
        self.date = QtWidgets.QLabel(self.widget)
        self.date.setStyleSheet("font-size: 13px;")
        self.date.setObjectName("date")
        self.verticalLayout_4.addWidget(self.date)
        self.location = QtWidgets.QLabel(self.widget)
        self.location.setStyleSheet("font-size: 13px;")
        self.location.setObjectName("location")
        self.verticalLayout_4.addWidget(self.location)
        self.interest = QtWidgets.QLabel(self.widget)
        self.interest.setStyleSheet("font-size: 13px;")
        self.interest.setObjectName("interest")
        self.verticalLayout_4.addWidget(self.interest)
        self.description = QtWidgets.QLabel(self.widget)
        self.description.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )
        self.description.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description.setObjectName("description")
        self.verticalLayout_4.addWidget(self.description)
        self.read_more = QtWidgets.QPushButton(self.widget)
        self.read_more.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more.setObjectName("read_more")
        self.verticalLayout_4.addWidget(self.read_more)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.widget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget1.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.photo_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo_2.setFont(font)
        self.photo_2.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo_2.setText("")
        self.photo_2.setPixmap(QtGui.QPixmap("../image/chess.jpg"))
        self.photo_2.setScaledContents(True)
        self.photo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_2.setObjectName("photo_2")
        self.horizontalLayout_3.addWidget(self.photo_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.event_2 = QtWidgets.QLabel(self.widget1)
        self.event_2.setStyleSheet("font-size: 18px;")
        self.event_2.setObjectName("event_2")
        self.verticalLayout_5.addWidget(self.event_2)
        self.date_2 = QtWidgets.QLabel(self.widget1)
        self.date_2.setStyleSheet("font-size: 13px;")
        self.date_2.setObjectName("date_2")
        self.verticalLayout_5.addWidget(self.date_2)
        self.location_2 = QtWidgets.QLabel(self.widget1)
        self.location_2.setStyleSheet("font-size: 13px;")
        self.location_2.setObjectName("location_2")
        self.verticalLayout_5.addWidget(self.location_2)
        self.interest_2 = QtWidgets.QLabel(self.widget1)
        self.interest_2.setStyleSheet("font-size: 13px;")
        self.interest_2.setObjectName("interest_2")
        self.verticalLayout_5.addWidget(self.interest_2)
        self.description_2 = QtWidgets.QLabel(self.widget1)
        self.description_2.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )
        self.description_2.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description_2.setObjectName("description_2")
        self.verticalLayout_5.addWidget(self.description_2)
        self.read_more_2 = QtWidgets.QPushButton(self.widget1)
        self.read_more_2.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more_2.setObjectName("read_more_2")
        self.verticalLayout_5.addWidget(self.read_more_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)

        # # box 3
        self.box3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.box3.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.box3.setObjectName("box3")
        self.horizontalLayout_box3 = QtWidgets.QHBoxLayout(self.box3)
        self.horizontalLayout_box3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_box3.setObjectName("horizontalLayout_6")
        self.photo_3 = QtWidgets.QLabel(self.box3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo_3.setFont(font)
        self.photo_3.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo_3.setText("")
        self.photo_3.setPixmap(QtGui.QPixmap("../image/chess.jpg"))
        self.photo_3.setScaledContents(True)
        self.photo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_3.setObjectName("photo_3")
        self.horizontalLayout_box3.addWidget(self.photo_3)
        self.verticalLayout_box3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_box3.setObjectName("verticalLayout_box3")
        self.event_3 = QtWidgets.QLabel(self.box3)
        self.event_3.setStyleSheet("font-size: 18px;")
        self.event_3.setObjectName("event_3")
        self.verticalLayout_box3.addWidget(self.event_3)
        self.date_3 = QtWidgets.QLabel(self.box3)
        self.date_3.setStyleSheet("font-size: 13px;")
        self.date_3.setObjectName("date_3")
        self.verticalLayout_box3.addWidget(self.date_3)
        self.location_3 = QtWidgets.QLabel(self.box3)
        self.location_3.setStyleSheet("font-size: 13px;")
        self.location_3.setObjectName("location_3")
        self.verticalLayout_box3.addWidget(self.location_3)
        self.interest_3 = QtWidgets.QLabel(self.box3)
        self.interest_3.setStyleSheet("font-size: 13px;")
        self.interest_3.setObjectName("interest_3")
        self.verticalLayout_box3.addWidget(self.interest_3)
        self.description_3 = QtWidgets.QLabel(self.box3)
        self.description_3.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )

        self.description_3.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description_3.setObjectName("description_3")
        self.verticalLayout_box3.addWidget(self.description_3)
        self.read_more_3 = QtWidgets.QPushButton(self.box3)
        self.read_more_3.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more_3.setObjectName("read_more_3")
        self.verticalLayout_box3.addWidget(self.read_more_3)
        self.horizontalLayout_box3.addLayout(self.verticalLayout_box3)

        # box 4
        self.box4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.box4.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.box4.setObjectName("box4")
        self.horizontalLayout_box4 = QtWidgets.QHBoxLayout(self.box4)
        self.horizontalLayout_box4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_box4.setObjectName("horizontalLayout_box4")
        self.photo_4 = QtWidgets.QLabel(self.box4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo_4.setFont(font)
        self.photo_4.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo_4.setText("")
        self.photo_4.setPixmap(QtGui.QPixmap("../image/chess.jpg"))
        self.photo_4.setScaledContents(True)
        self.photo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_4.setObjectName("photo_4")
        self.horizontalLayout_box4.addWidget(self.photo_4)
        self.verticalLayout_box4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_box4.setObjectName("verticalLayout_box3")
        self.event_4 = QtWidgets.QLabel(self.box4)
        self.event_4.setStyleSheet("font-size: 18px;")
        self.event_4.setObjectName("event_4")
        self.verticalLayout_box4.addWidget(self.event_4)
        self.date_4 = QtWidgets.QLabel(self.box4)
        self.date_4.setStyleSheet("font-size: 13px;")
        self.date_4.setObjectName("date_4")
        self.verticalLayout_box4.addWidget(self.date_4)
        self.location_4 = QtWidgets.QLabel(self.box4)
        self.location_4.setStyleSheet("font-size: 13px;")
        self.location_4.setObjectName("location_4")
        self.verticalLayout_box4.addWidget(self.location_4)
        self.interest_4 = QtWidgets.QLabel(self.box4)
        self.interest_4.setStyleSheet("font-size: 13px;")
        self.interest_4.setObjectName("interest_4")
        self.verticalLayout_box4.addWidget(self.interest_4)
        self.description_4 = QtWidgets.QLabel(self.box4)
        self.description_4.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )

        self.description_4.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description_4.setObjectName("description_4")
        self.verticalLayout_box4.addWidget(self.description_4)
        self.read_more_4 = QtWidgets.QPushButton(self.box4)
        self.read_more_4.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more_4.setObjectName("read_more_4")
        self.verticalLayout_box4.addWidget(self.read_more_4)
        self.horizontalLayout_box4.addLayout(self.verticalLayout_box4)

        # box 5
        self.box5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.box5.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.box5.setObjectName("box5")
        self.horizontalLayout_box5 = QtWidgets.QHBoxLayout(self.box5)
        self.horizontalLayout_box5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_box5.setObjectName("horizontalLayout_box5")
        self.photo_5 = QtWidgets.QLabel(self.box5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo_5.setFont(font)
        self.photo_5.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo_5.setText("")
        self.photo_5.setPixmap(QtGui.QPixmap("../image/chess.jpg"))
        self.photo_5.setScaledContents(True)
        self.photo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_5.setObjectName("photo_5")
        self.horizontalLayout_box5.addWidget(self.photo_5)
        self.verticalLayout_box5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_box5.setObjectName("verticalLayout_box5")
        self.event_5 = QtWidgets.QLabel(self.box5)
        self.event_5.setStyleSheet("font-size: 18px;")
        self.event_5.setObjectName("event_5")
        self.verticalLayout_box5.addWidget(self.event_5)
        self.date_5 = QtWidgets.QLabel(self.box5)
        self.date_5.setStyleSheet("font-size: 13px;")
        self.date_5.setObjectName("date_5")
        self.verticalLayout_box5.addWidget(self.date_5)
        self.location_5 = QtWidgets.QLabel(self.box5)
        self.location_5.setStyleSheet("font-size: 13px;")
        self.location_5.setObjectName("location_5")
        self.verticalLayout_box5.addWidget(self.location_5)
        self.interest_5 = QtWidgets.QLabel(self.box5)
        self.interest_5.setStyleSheet("font-size: 13px;")
        self.interest_5.setObjectName("interest_5")
        self.verticalLayout_box5.addWidget(self.interest_5)
        self.description_5 = QtWidgets.QLabel(self.box5)
        self.description_5.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )

        self.description_5.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description_5.setObjectName("description_5")
        self.verticalLayout_box5.addWidget(self.description_5)
        self.read_more_5 = QtWidgets.QPushButton(self.box5)
        self.read_more_5.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more_5.setObjectName("read_more_4")
        self.verticalLayout_box5.addWidget(self.read_more_5)
        self.horizontalLayout_box5.addLayout(self.verticalLayout_box5)

        # box 6

        self.box6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.box6.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.box6.setObjectName("box5")
        self.horizontalLayout_box6 = QtWidgets.QHBoxLayout(self.box6)
        self.horizontalLayout_box6.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_box6.setObjectName("horizontalLayout_box6")
        self.photo_6 = QtWidgets.QLabel(self.box6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo_6.setFont(font)
        self.photo_6.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo_6.setText("")
        self.photo_6.setPixmap(QtGui.QPixmap("../image/chess.jpg"))
        self.photo_6.setScaledContents(True)
        self.photo_6.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_6.setObjectName("photo_6")
        self.horizontalLayout_box6.addWidget(self.photo_6)
        self.verticalLayout_box6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_box6.setObjectName("verticalLayout_box6")
        self.event_6 = QtWidgets.QLabel(self.box6)
        self.event_6.setStyleSheet("font-size: 18px;")
        self.event_6.setObjectName("event_6")
        self.verticalLayout_box6.addWidget(self.event_6)
        self.date_6 = QtWidgets.QLabel(self.box6)
        self.date_6.setStyleSheet("font-size: 13px;")
        self.date_6.setObjectName("date_6")
        self.verticalLayout_box6.addWidget(self.date_6)
        self.location_6 = QtWidgets.QLabel(self.box6)
        self.location_6.setStyleSheet("font-size: 13px;")
        self.location_6.setObjectName("location_6")
        self.verticalLayout_box6.addWidget(self.location_6)
        self.interest_6 = QtWidgets.QLabel(self.box6)
        self.interest_6.setStyleSheet("font-size: 13px;")
        self.interest_6.setObjectName("interest_6")
        self.verticalLayout_box6.addWidget(self.interest_6)
        self.description_6 = QtWidgets.QLabel(self.box6)
        self.description_6.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )

        self.description_6.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description_6.setObjectName("description_6")
        self.verticalLayout_box6.addWidget(self.description_6)
        self.read_more_6 = QtWidgets.QPushButton(self.box6)
        self.read_more_6.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more_6.setObjectName("read_more_6")
        self.verticalLayout_box6.addWidget(self.read_more_6)
        self.horizontalLayout_box6.addLayout(self.verticalLayout_box6)

        # box 7

        self.box7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.box7.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.box7.setObjectName("box7")
        self.horizontalLayout_box7 = QtWidgets.QHBoxLayout(self.box7)
        self.horizontalLayout_box7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_box7.setObjectName("horizontalLayout_box7")
        self.photo_7 = QtWidgets.QLabel(self.box7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo_7.setFont(font)
        self.photo_7.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo_7.setText("")
        self.photo_7.setScaledContents(True)
        self.photo_7.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_7.setObjectName("photo_7")
        self.horizontalLayout_box7.addWidget(self.photo_7)
        self.verticalLayout_box7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_box7.setObjectName("verticalLayout_box7")
        self.event_7 = QtWidgets.QLabel(self.box7)
        self.event_7.setStyleSheet("font-size: 18px;")
        self.event_7.setObjectName("event_7")
        self.verticalLayout_box7.addWidget(self.event_7)
        self.date_7 = QtWidgets.QLabel(self.box7)
        self.date_7.setStyleSheet("font-size: 13px;")
        self.date_7.setObjectName("date_7")
        self.verticalLayout_box7.addWidget(self.date_7)
        self.location_7 = QtWidgets.QLabel(self.box7)
        self.location_7.setStyleSheet("font-size: 13px;")
        self.location_7.setObjectName("location_7")
        self.verticalLayout_box7.addWidget(self.location_7)
        self.interest_7 = QtWidgets.QLabel(self.box7)
        self.interest_7.setStyleSheet("font-size: 13px;")
        self.interest_7.setObjectName("interest_7")
        self.verticalLayout_box7.addWidget(self.interest_7)
        self.description_7 = QtWidgets.QLabel(self.box7)
        self.description_7.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )

        self.description_7.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description_7.setObjectName("description_7")
        self.verticalLayout_box7.addWidget(self.description_7)
        self.read_more_7 = QtWidgets.QPushButton(self.box7)
        self.read_more_7.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more_7.setObjectName("read_more_7")
        self.verticalLayout_box7.addWidget(self.read_more_7)
        self.horizontalLayout_box7.addLayout(self.verticalLayout_box7)

        # box 8
        self.box8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.box8.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.box8.setObjectName("box8")
        self.horizontalLayout_box8 = QtWidgets.QHBoxLayout(self.box8)
        self.horizontalLayout_box8.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_box8.setObjectName("horizontalLayout_box8")
        self.photo_8 = QtWidgets.QLabel(self.box8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo_8.setFont(font)
        self.photo_8.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo_8.setText("")
        self.photo_8.setScaledContents(True)
        self.photo_8.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_8.setObjectName("photo_8")
        self.horizontalLayout_box8.addWidget(self.photo_8)
        self.verticalLayout_box8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_box8.setObjectName("verticalLayout_box8")
        self.event_8 = QtWidgets.QLabel(self.box8)
        self.event_8.setStyleSheet("font-size: 18px;")
        self.event_8.setObjectName("event_8")
        self.verticalLayout_box8.addWidget(self.event_8)
        self.date_8 = QtWidgets.QLabel(self.box8)
        self.date_8.setStyleSheet("font-size: 13px;")
        self.date_8.setObjectName("date_8")
        self.verticalLayout_box8.addWidget(self.date_8)
        self.location_8 = QtWidgets.QLabel(self.box8)
        self.location_8.setStyleSheet("font-size: 13px;")
        self.location_8.setObjectName("location_8")
        self.verticalLayout_box8.addWidget(self.location_8)
        self.interest_8 = QtWidgets.QLabel(self.box8)
        self.interest_8.setStyleSheet("font-size: 13px;")
        self.interest_8.setObjectName("interest_8")
        self.verticalLayout_box8.addWidget(self.interest_8)
        self.description_8 = QtWidgets.QLabel(self.box8)
        self.description_8.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )

        self.description_8.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description_8.setObjectName("description_8")
        self.verticalLayout_box8.addWidget(self.description_8)
        self.read_more_8 = QtWidgets.QPushButton(self.box8)
        self.read_more_8.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more_8.setObjectName("read_more_8")
        self.verticalLayout_box8.addWidget(self.read_more_8)
        self.horizontalLayout_box8.addLayout(self.verticalLayout_box8)

        # box 9
        self.box9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.box9.setStyleSheet(
            "margin-bottom: 8px;\n"
            "max-height: 500px;\n"
            "background:white;\n"
            "border-radius: 5px;"
        )
        self.box9.setObjectName("box9")
        self.horizontalLayout_box9 = QtWidgets.QHBoxLayout(self.box9)
        self.horizontalLayout_box9.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_box9.setObjectName("horizontalLayout_box9")
        self.photo_9 = QtWidgets.QLabel(self.box9)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.photo_9.setFont(font)
        self.photo_9.setStyleSheet(
            "display: inline-block;\n"
            "min-width: 100px;\n"
            "min-height: 100px;\n"
            "max-width: 280px;\n"
            "max-height: 300px;\n"
            "margin-left:9px;\n"
            "border-radius: 3px;\n"
            ""
        )
        self.photo_9.setText("")
        self.photo_9.setScaledContents(True)
        self.photo_9.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_9.setObjectName("photo_9")
        self.horizontalLayout_box9.addWidget(self.photo_9)
        self.verticalLayout_box9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_box9.setObjectName("verticalLayout_box9")
        self.event_9 = QtWidgets.QLabel(self.box9)
        self.event_9.setStyleSheet("font-size: 18px;")
        self.event_9.setObjectName("event_9")
        self.verticalLayout_box9.addWidget(self.event_9)
        self.date_9 = QtWidgets.QLabel(self.box9)
        self.date_9.setStyleSheet("font-size: 13px;")
        self.date_9.setObjectName("date_9")
        self.verticalLayout_box9.addWidget(self.date_9)
        self.location_9 = QtWidgets.QLabel(self.box9)
        self.location_9.setStyleSheet("font-size: 13px;")
        self.location_9.setObjectName("location_9")
        self.verticalLayout_box9.addWidget(self.location_9)
        self.interest_9 = QtWidgets.QLabel(self.box9)
        self.interest_9.setStyleSheet("font-size: 13px;")
        self.interest_9.setObjectName("interest_9")
        self.verticalLayout_box9.addWidget(self.interest_9)
        self.description_9 = QtWidgets.QLabel(self.box9)
        self.description_9.setStyleSheet(
            "font-size: 13px;\n" "min-height: 100px;\n" "max-width: 300px;"
        )

        self.description_9.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.description_9.setObjectName("description_9")
        self.verticalLayout_box9.addWidget(self.description_9)
        self.read_more_9 = QtWidgets.QPushButton(self.box9)
        self.read_more_9.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 10px 23px;\n"
            "margin: 10px 60px 10px 60px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 13px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}\n"
            ""
        )
        self.read_more_9.setObjectName("read_more_9")
        self.verticalLayout_box9.addWidget(self.read_more_9)
        self.horizontalLayout_box9.addLayout(self.verticalLayout_box9)
        # THIS IS THE MAIN LAYOUT
        self.photo.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))
        self.photo_2.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))
        self.photo_3.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))
        self.photo_4.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))
        self.photo_5.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))
        self.photo_6.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))
        self.photo_7.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))
        self.photo_8.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))
        self.photo_9.setPixmap(QtGui.QPixmap(os.path.join(path, "image/chess.jpg")))

        box_set = [
            self.widget,
            self.widget1,
            self.box3,
            self.box4,
            self.box5,
            self.box6,
            self.box7,
            self.box8,
            self.box9,
        ]

        # For LOOP for EINAV <3
        for i, j in zip(box_set, range(len(event_id_list))):
            self.gridLayout.addWidget(i, j, 0, 1, 1, QtCore.Qt.AlignVCenter)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.main_board.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.main_board)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addWidget(self.frame, 0, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setStyleSheet("padding-right: 5cm;")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4.addWidget(self.widget_4, 0, 2, 1, 1)

        spacerItem = QtWidgets.QSpacerItem(
            10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _, event_details = show_events()
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.app_logo.setText(_translate("Form", "GoldApp"))
        self.events_location.setText(
            _translate(
                "Form",
                '<html><head/><body><p align="center">Local Events and Meetups<span id="events_location" class="events_location">:</span></p></body></html> ',
            )
        )
        event_set = [
            self.event,
            self.event_2,
            self.event_3,
            self.event_4,
            self.event_5,
            self.event_6,
            self.event_7,
            self.event_8,
            self.event_9,
        ]

        date_set = [
            self.date,
            self.date_2,
            self.date_3,
            self.date_4,
            self.date_5,
            self.date_6,
            self.date_7,
            self.date_8,
            self.date_9,
        ]

        location_set = [
            self.location,
            self.location_2,
            self.location_3,
            self.location_4,
            self.location_5,
            self.location_6,
            self.location_7,
            self.location_8,
            self.location_9,
        ]

        interest_set = [
            self.interest,
            self.interest_2,
            self.interest_3,
            self.interest_4,
            self.interest_5,
            self.interest_6,
            self.interest_7,
            self.interest_8,
            self.interest_9,
        ]

        description_set = [
            self.description,
            self.description_2,
            self.description_3,
            self.description_4,
            self.description_5,
            self.description_6,
            self.description_7,
            self.description_8,
            self.description_9,
        ]

        read_more_set = [
            self.read_more,
            self.read_more_2,
            self.read_more_3,
            self.read_more_4,
            self.read_more_5,
            self.read_more_6,
            self.read_more_7,
            self.read_more_8,
            self.read_more_9,
        ]

        for field, info in zip(event_set, event_details):
            print(field)
            print(info, field)
            data = json.loads(info[0])
            field.setText(
                _translate(
                    "Form",
                    'Event<span class="event">: ' + str(data.get("name")) + "</span>",
                )
            )

        for field, info in zip(date_set, event_details):
            data = json.loads(info[0])
            field.setText(
                _translate(
                    "Form",
                    'Date & Time<span class="date">: '
                    + data.get("event_date")
                    + "</span>",
                )
            )

        for field, info in zip(location_set, event_details):
            data = json.loads(info[0])
            field.setText(
                _translate(
                    "Form",
                    'Location<span class="address">: '
                    + data.get("address")
                    + "</span>",
                )
            )

        for field, info in zip(interest_set, event_details):
            data = json.loads(info[0])
            print(data.get("interest"))
            field.setText(
                _translate(
                    "Form",
                    'Interest<span class="interest">: '
                    + data.get("interest")
                    + "</span>",
                )
            )
        for field, info in zip(description_set, event_details):
            data = json.loads(info[0])
            print(data.get("information"))
            field.setText(
                _translate(
                    "Form",
                    'Description<span class="desc">: '
                    + data.get("information")
                    + "</span>",
                )
            )
        for i in read_more_set:
            i.setText(_translate("Form", "Read More"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
