# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/examples/new_account_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(658, 851)
        Form.setMinimumSize(QtCore.QSize(1200, 600))
        Form.setMaximumSize(QtCore.QSize(1800, 1200))
        Form.setStyleSheet("background-color: rgb(220, 221, 255);")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.app_logo = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.app_logo.setFont(font)
        self.app_logo.setStyleSheet(
            "QLabel{\n"
            "color: rgb(255, 203, 99);\n"
            "background-color: white;\n"
            "border-color: black;\n"
            "border-radius: 10px;\n"
            "border-style: none;\n"
            "margin-top: 5px;\n"
            "margin-bottom: 5px;\n"
            "padding-left: 10px;\n"
            "padding-right: 10px;\n"
            "margin-left: 0px;\n"
            "margin-right: 0px;\n"
            "}"
        )
        self.app_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.app_logo.setObjectName("app_logo")
        self.horizontalLayout_5.addWidget(self.app_logo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setStyleSheet("margin-bottom: 2px")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 9, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.email_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("margin-right: 130px;")
        self.email_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.email_label.setObjectName("email_label")
        self.horizontalLayout.addWidget(self.email_label)
        self.email_input = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(18)
        self.email_input.setFont(font)
        self.email_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_input.setText("")
        self.email_input.setObjectName("email_input")
        self.horizontalLayout.addWidget(self.email_input)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setStyleSheet("margin-bottom: 0px")
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.last_label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.last_label.setFont(font)
        self.last_label.setStyleSheet("margin-right: 76px;")
        self.last_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.last_label.setObjectName("last_label")
        self.horizontalLayout_2.addWidget(self.last_label)
        self.last_input = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.last_input.setFont(font)
        self.last_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.last_input.setObjectName("last_input")
        self.horizontalLayout_2.addWidget(self.last_input)
        self.gridLayout_3.addWidget(self.widget1, 1, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.frame)
        self.widget2.setStyleSheet("margin-bottom: 0px")
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.first_label = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.first_label.setFont(font)
        self.first_label.setStyleSheet("margin-right: 74px;")
        self.first_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.first_label.setObjectName("first_label")
        self.horizontalLayout_3.addWidget(self.first_label)
        self.first_input = QtWidgets.QLineEdit(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.first_input.setFont(font)
        self.first_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.first_input.setObjectName("first_input")
        self.horizontalLayout_3.addWidget(self.first_input)
        self.gridLayout_3.addWidget(self.widget2, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.interests_lable = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.interests_lable.setFont(font)
        self.interests_lable.setStyleSheet("margin-bottom: 0px;\n" "margin-top: 10px;")
        self.interests_lable.setObjectName("interests_lable")
        self.verticalLayout.addWidget(self.interests_lable)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 3, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 3, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 3, 3, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 1, 3, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 1, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 2, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(14)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 4, 0, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.frame)
        self.widget3.setStyleSheet("margin-bottom: 0px;")
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.phone_label = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.phone_label.setFont(font)
        self.phone_label.setStyleSheet("margin-right: 26px;")
        self.phone_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.phone_label.setObjectName("phone_label")
        self.horizontalLayout_4.addWidget(self.phone_label)
        self.phone_input = QtWidgets.QLineEdit(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.phone_input.setFont(font)
        self.phone_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phone_input.setText("")
        self.phone_input.setObjectName("phone_input")
        self.horizontalLayout_4.addWidget(self.phone_input)
        self.gridLayout_3.addWidget(self.widget3, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_3.addItem(spacerItem1)
        self.create_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.create_button.setFont(font)
        self.create_button.setStyleSheet(
            "QPushButton{\n"
            "background-color:  rgb(255, 203, 99);\n"
            "border: none;\n"
            "border-radius: 10px;\n"
            "color: white;\n"
            "padding: 15px 32px;\n"
            "text-align: center;\n"
            "text-decoration: none;\n"
            "display: inline-block;\n"
            "font-size: 16px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background-color:  rgb(255, 220, 99);\n"
            "}"
        )
        self.create_button.setObjectName("create_button")
        self.verticalLayout_3.addWidget(self.create_button)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.app_logo.setText(_translate("Form", "GoldApp"))
        self.email_label.setText(_translate("Form", "Email:"))
        self.last_label.setText(_translate("Form", "Last name:"))
        self.first_label.setText(_translate("Form", "First name:"))
        self.interests_lable.setText(_translate("Form", "Choose your interests:"))
        self.checkBox_3.setText(_translate("Form", "Cinema/Theater"))
        self.checkBox_6.setText(_translate("Form", "Music"))
        self.checkBox_9.setText(_translate("Form", "Taking walks"))
        self.checkBox_2.setText(_translate("Form", "Fishing"))
        self.checkBox_8.setText(_translate("Form", "Baking"))
        self.checkBox_7.setText(_translate("Form", "Board games"))
        self.checkBox.setText(_translate("Form", "Cooking"))
        self.checkBox_5.setText(_translate("Form", "Hunting"))
        self.checkBox_4.setText(_translate("Form", "Art"))
        self.phone_label.setText(_translate("Form", "Phone number:"))
        self.create_button.setText(_translate("Form", "Create"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
